parameters:
  - name: variables
    type: string
  - name: environment
    type: string
  - name: json
    type: object

stages:
  - stage: deploy
    variables:
      - group: ${{ parameters.variables }}
    jobs:
      - ${{ each deployment in parameters.json }}:
          - deployment: deploy_${{ replace(deployment.name, '-', '_') }}
            displayName: Deploy ${{ upper(deployment.name) }}
            environment: ${{ parameters .environment }}
            pool:
              name: $(agentPool)
            workspace:
              clean: all
            strategy:
              runOnce:
                deploy:
                  steps:
                    - bash: |
                        echo "name ${{ deployment.name }}"
                        echo "path ${{ deployment.path }}"
                        echo "serviceName $(serviceName)"
                        echo "serviceConnection $(serviceConnection)"
                    - task: AzureCLI@2
                      inputs:
                        azureSubscription: ${{ variables['serviceConnection'] }}
                        scriptType: pscore
                        scriptLocation: inlineScript
                        inlineScript: |
                          az account get-access-token --query accessToken