parameters:
  - name: variables
    type: string
  - name: environment
    type: string
  - name: serviceConnection
    type: string
  - name: resourceType
    type: string
    values:
      - datasources
      - indexes
      - indexers
      - skillsets
  - name: jsonPath
    type: string
  - name: agentPool
    type: object
    default:
      vmImage: ubuntu-latest

stages:
  - stage: deploy
    variables:
      - group: ${{ parameters.variables }}
    jobs:
      - deployment: deploy_${{ parameters.resourceType }}
        displayName: Deploy ${{ parameters.resourceType }}
        environment: ${{ parameters .environment }}
        pool: ${{ parameters.agentPool }}
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: create resource ${{ parameters.resourceType }}
                  inputs:
                    azureSubscription: ${{ parameters.serviceConnection }}
                    scriptType: pscore
                    scriptLocation: inlineScript
                    inlineScript: |
                      $apiVersion = "2024-07-01"
                      
                      Write-Host "creating ${{ parameters.resourceType }}, in $(serviceName), using data from ${{ parameters.jsonPath }}" 

                      ls
                      
                      $json = Get-Content ${{ parameters.jsonPath }}/${{ parameters.environment }}/data.json | ConvertFrom-Json
                      
                      foreach ($resource in $json) {
                        Write-Host "Processing ($resource.name)"
                      }
#                      $body = Get-Content ${{ deployment.payload }} | ConvertFrom-Json | ConvertTo-Json -Compress -Depth 10
#                      $uri = "https://$(serviceName).search.windows.net/${{ parameters.resourceType }}('${{ deployment.name }}')?api-version=${apiVersion}"
#
#                      $tokenRequest = az account get-access-token --scope https://search.azure.com/.default | ConvertFrom-Json
#                      $token = "Bearer {0}" -f $tokenRequest.accessToken
#
#                      Write-Host $tokenRequest.accessToken
#                      Write-Host "Invoke-RestMethod -Method PUT -Uri $uri -Body $body"
#
#                      Invoke-RestMethod -Method PUT -Uri $uri -Body $body -Headers @{
#                        "Authorization" = $token
#                        "Content-Type"  = "application/json"
#                      }