parameters:
  - name: variables
    type: string
  - name: json
    type: object

stages:
  - stage: deploy
    variables:
      - group: ${{ parameters.variables }}
    jobs:
      - ${{ each deployment in parameters.json }}:
          - deployment: deploy_${{ replace(deployment.name, '-', '_') }}
            displayName: Deploy ${{ upper(deployment.name) }}
            environment: $(environment)
            pool:
              name: $(agent-pool)
            workspace:
              clean: all
            strategy:
              runOnce:
                deploy:
                  steps:
                    - bash: |
                        echo "name ${{ deployment.name }}"
                        echo "path ${{ deployment.path }}"
                        echo "service-name $(service-name)"